# Generated by Django 4.0.4 on 2022-06-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='ServicesImg',
        ),
    ]
