# Generated by Django 4.0.4 on 2022-07-14 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
