# Generated by Django 4.0.4 on 2022-07-14 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_page_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='telegram',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
